import { VideoItem, DownloadItem, TranscriptionResult, SummaryReport, RecordingItem, CallRecordingItem } from '../types';

export const MOCK_VIDEOS: VideoItem[] = [
  {
    id: '1',
    title: 'Building AI-Powered Mobile Apps with React Native in 2026',
    description: 'Learn how to integrate AI features into your React Native applications.',
    thumbnail: 'https://picsum.photos/seed/vid1/640/360',
    duration: '15:42',
    views: '1.2M',
    platform: 'youtube',
    channelName: 'Tech Academy',
    channelAvatar: 'https://picsum.photos/seed/ch1/100/100',
    publishedAt: '2 days ago',
    url: 'https://youtube.com/watch?v=example1',
  },
  {
    id: '2',
    title: 'Amazing Sunset Timelapse at Grand Canyon National Park',
    description: 'Watch this breathtaking timelapse of sunset at the Grand Canyon.',
    thumbnail: 'https://picsum.photos/seed/vid2/640/360',
    duration: '3:28',
    views: '856K',
    platform: 'facebook',
    channelName: 'Nature Explorers',
    channelAvatar: 'https://picsum.photos/seed/ch2/100/100',
    publishedAt: '1 week ago',
    url: 'https://facebook.com/watch/example2',
  },
  {
    id: '3',
    title: 'Dance Challenge Goes Viral - 50 Million Views!',
    description: 'The latest dance challenge that took the internet by storm.',
    thumbnail: 'https://picsum.photos/seed/vid3/640/360',
    duration: '0:45',
    views: '50M',
    platform: 'tiktok',
    channelName: '@dancequeen',
    publishedAt: '3 hours ago',
    url: 'https://tiktok.com/@dancequeen/video/example3',
  },
  {
    id: '4',
    title: 'Behind the Scenes: Fashion Week 2026 Paris Collection',
    description: 'Exclusive backstage footage from Paris Fashion Week 2026.',
    thumbnail: 'https://picsum.photos/seed/vid4/640/360',
    duration: '8:15',
    views: '2.3M',
    platform: 'instagram',
    channelName: 'FashionHub',
    channelAvatar: 'https://picsum.photos/seed/ch4/100/100',
    publishedAt: '5 days ago',
    url: 'https://instagram.com/reel/example4',
  },
  {
    id: '5',
    title: 'The Future of Remote Work: Expert Panel Discussion',
    description: 'Industry leaders discuss the evolution of remote work culture.',
    thumbnail: 'https://picsum.photos/seed/vid5/640/360',
    duration: '45:00',
    views: '124K',
    platform: 'linkedin',
    channelName: 'Business Insights',
    channelAvatar: 'https://picsum.photos/seed/ch5/100/100',
    publishedAt: '1 day ago',
    url: 'https://linkedin.com/video/example5',
  },
  {
    id: '6',
    title: 'Cooking Masterclass: Perfect Italian Pasta from Scratch',
    description: 'Chef Marco shows you how to make authentic Italian pasta.',
    thumbnail: 'https://picsum.photos/seed/vid6/640/360',
    duration: '22:10',
    views: '3.7M',
    platform: 'youtube',
    channelName: 'Chef Marco',
    channelAvatar: 'https://picsum.photos/seed/ch6/100/100',
    publishedAt: '4 days ago',
    url: 'https://youtube.com/watch?v=example6',
  },
  {
    id: '7',
    title: 'Street Art Tour: The Best Murals in Berlin',
    description: 'Explore the incredible street art scene in Berlin.',
    thumbnail: 'https://picsum.photos/seed/vid7/640/360',
    duration: '12:33',
    views: '445K',
    platform: 'facebook',
    channelName: 'Urban Explorer',
    publishedAt: '2 weeks ago',
    url: 'https://facebook.com/watch/example7',
    isLive: false,
  },
  {
    id: '8',
    title: 'LIVE: Music Festival 2026 - Main Stage',
    description: 'Watch the live performance from Music Festival 2026.',
    thumbnail: 'https://picsum.photos/seed/vid8/640/360',
    duration: 'LIVE',
    views: '15K watching',
    platform: 'youtube',
    channelName: 'Festival Live',
    publishedAt: 'Streaming now',
    url: 'https://youtube.com/watch?v=example8',
    isLive: true,
  },
];

export const MOCK_DOWNLOADS: DownloadItem[] = [
  {
    id: 'd1',
    url: 'https://youtube.com/watch?v=example1',
    title: 'Building AI-Powered Mobile Apps',
    thumbnail: 'https://picsum.photos/seed/vid1/640/360',
    platform: 'youtube',
    mediaType: 'video',
    quality: '1080p',
    size: '245 MB',
    progress: 100,
    status: 'completed',
    createdAt: new Date('2026-03-09'),
  },
  {
    id: 'd2',
    url: 'https://instagram.com/reel/example4',
    title: 'Fashion Week 2026 Highlights',
    thumbnail: 'https://picsum.photos/seed/vid4/640/360',
    platform: 'instagram',
    mediaType: 'video',
    quality: '720p',
    size: '85 MB',
    progress: 67,
    status: 'downloading',
    createdAt: new Date('2026-03-10'),
  },
  {
    id: 'd3',
    url: 'https://tiktok.com/@dancequeen/video/example3',
    title: 'Dance Challenge Viral Video',
    platform: 'tiktok',
    mediaType: 'video',
    quality: '720p',
    size: '12 MB',
    progress: 0,
    status: 'pending',
    createdAt: new Date('2026-03-10'),
  },
];

export const MOCK_TRANSCRIPTIONS: TranscriptionResult[] = [
  {
    id: 't1',
    text: 'Welcome to today\'s tutorial on building AI-powered mobile applications.',
    timestamp: 0,
    duration: 3.5,
    language: 'en',
    confidence: 0.98,
  },
  {
    id: 't2',
    text: 'We\'ll be using React Native with TypeScript for our development framework.',
    timestamp: 3.5,
    duration: 4.2,
    language: 'en',
    confidence: 0.96,
  },
  {
    id: 't3',
    text: 'First, let\'s set up our project structure and install the necessary dependencies.',
    timestamp: 7.7,
    duration: 3.8,
    language: 'en',
    confidence: 0.97,
  },
  {
    id: 't4',
    text: 'The AI integration will use a combination of on-device and cloud-based processing.',
    timestamp: 11.5,
    duration: 4.5,
    language: 'en',
    confidence: 0.94,
  },
  {
    id: 't5',
    text: 'This approach gives us the best balance between speed and accuracy.',
    timestamp: 16.0,
    duration: 3.2,
    language: 'en',
    confidence: 0.95,
  },
];

export const MOCK_SUMMARY: SummaryReport = {
  id: 's1',
  title: 'Building AI-Powered Mobile Apps',
  mediaUrl: 'https://youtube.com/watch?v=example1',
  mediaType: 'video',
  summary: 'This comprehensive tutorial covers the process of building AI-powered mobile applications using React Native and TypeScript. The video demonstrates integration of various AI services including natural language processing, image recognition, and speech-to-text capabilities. Key takeaways include best practices for on-device AI processing, cloud API integration patterns, and performance optimization techniques for mobile AI applications.',
  keyPoints: [
    'React Native with TypeScript is the recommended framework for AI mobile apps',
    'On-device AI processing provides faster response times for basic operations',
    'Cloud-based AI services are essential for complex processing tasks',
    'Proper caching strategies can reduce API costs by up to 60%',
    'Progressive loading patterns improve user experience significantly',
    'Security considerations are crucial when handling AI model data',
  ],
  sentiment: 'positive',
  topics: ['Mobile Development', 'Artificial Intelligence', 'React Native', 'TypeScript', 'Machine Learning'],
  wordCount: 3450,
  readingTime: '14 min',
  generatedAt: new Date('2026-03-10'),
};

export const MOCK_RECORDINGS: RecordingItem[] = [
  {
    id: 'r1',
    title: 'Meeting Notes - March 9',
    filePath: '/recordings/meeting_notes_mar9.m4a',
    duration: 1845,
    size: '15.2 MB',
    format: 'M4A',
    createdAt: new Date('2026-03-09T14:30:00'),
    effects: {
      bass: 50,
      treble: 50,
      echo: 0,
      volume: 100,
      reverb: 0,
      noiseCancellation: true,
      equalizer: [50, 50, 50, 50, 50, 50, 50, 50],
    },
  },
  {
    id: 'r2',
    title: 'Voice Memo - Ideas',
    filePath: '/recordings/voice_memo_ideas.m4a',
    duration: 320,
    size: '2.6 MB',
    format: 'M4A',
    createdAt: new Date('2026-03-08T09:15:00'),
    effects: {
      bass: 60,
      treble: 45,
      echo: 10,
      volume: 100,
      reverb: 5,
      noiseCancellation: false,
      equalizer: [55, 60, 50, 45, 50, 55, 60, 50],
    },
  },
];

export const MOCK_CALL_RECORDINGS: CallRecordingItem[] = [
  {
    id: 'cr1',
    contactName: 'John Smith',
    phoneNumber: '+1 (555) 123-4567',
    callType: 'incoming',
    duration: 342,
    filePath: '/call_recordings/john_smith_mar9.m4a',
    createdAt: new Date('2026-03-09T16:45:00'),
    isConsentGiven: true,
  },
  {
    id: 'cr2',
    contactName: 'Sarah Johnson',
    phoneNumber: '+1 (555) 987-6543',
    callType: 'outgoing',
    duration: 189,
    filePath: '/call_recordings/sarah_johnson_mar8.m4a',
    createdAt: new Date('2026-03-08T11:20:00'),
    isConsentGiven: true,
  },
];

export const formatDuration = (seconds: number): string => {
  const hrs = Math.floor(seconds / 3600);
  const mins = Math.floor((seconds % 3600) / 60);
  const secs = seconds % 60;
  if (hrs > 0) {
    return `${hrs}:${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
  }
  return `${mins}:${secs.toString().padStart(2, '0')}`;
};

export const formatDate = (date: Date): string => {
  return date.toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
};
